controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

hello_world:
    path: /hello
    controller: App\Controller\HelloWorldController::helloWorld
    methods: ['GET']
register_donation:
    path: /new
    controller: App\Controller\DonationController::newDonation
    methods: ['POST']
