controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

register_donation:
    path: /new
    controller: App\Controller\DonationController::newDonation
    methods: ['POST']

find_one_donation:
    path: /dashboard/{id}
    controller: App\Controller\DashboardController::listDonation
    methods: ['GET']

find_all_donations:
    path: /dashboard
    controller: App\Controller\DashboardController::listDonations
    methods: ['GET']
